---
- name: install apache using line in file module
  hosts: webservers
  become: true
  tasks:
          - name: install 
            yum:
                    name: httpd
                    state: latest
          - name: start service
            service:
                    name: httpd
                    state: started
                    enabled: true
          - name: create index.html
            lineinfile:
                    path: /var/www/html/index.html
                    line: 'Hello from {{ ansible_hostname }}'
                    state: present
                    mode: 0644
                    owner: root
                    group: root
                    create: yes
          - name: all in firewall
            firewalld:
                    service: http
                    permanent: true
                    immediate: true
                    state: enabled
          - name: retsrat 
            service:
                    name: httpd
                    state: restarted
