---
- name: testing for errors
  hosts: webservers
  become: true
  tasks:
          - name: install httpd
            yum:
                    name: http
                    state: latest
            ignore_errors: true

          - name: create a file
            file:
                    path: /tmp/myerror.txt
                    state: touch
...
