---
- name: install and start a few services as well as block, rescue, always
  hosts: all
  become: true
  vars:
          - webpackage: httpd
          - webservice: httpd
          - users:
                  - andrew
                  - albert
                  - christian
                  - edward
  tasks:
          - name: install {{ webpackage }}
            block:
                    - name: install
                      package:
                              name: "{{ webpackage }}"
                              state: latest
                    - name: start the {{ webservice }}
                      service:
                              name: "{{ webservice }}"
                              enabled: true
                              state: started
                    - name: start and enable firwalld
                      service:
                              name: firewalld
                              state: started
                              enabled: true
                    - name: add http to the firewall
                      firewalld:
                              service: httpd
                              permanent: true
                              immediate: true
                              state: enabled
            when: inventory_hostname in groups['dev']
            rescue:
                    - name: rescue the above failure
                      firewalld:
                              service: http
                              permanent: true
                              immediate: true
                              state: enabled
                    - name: download the index.html file
                      get_url:
                              url: http://192.168.226.137/exam/index.html.j2
                              dest: /var/www/html/index.html
                      notify:
                              - restart_httpd
  handlers:
          - name: restart_httpd
            service:
                    name: httpd
                    state: restarted


            when: inventory_hostname in groups['dev']
