---
- name: some tasks to execute
  hosts: webservers
  become: true
  tasks:
          - name: create my block
            block:
                    - name: update my packages
                      yum:
                              name: http
                              state: latest
                    - name: create a file
                      file:
                              path: /tmp/myblockfile.txt
                              state: touch
                              owner: root
                              group: root
                    - name: create a user
                      user:
                              name: blockuser
                              state: present
            rescue:
                    - name: create a failed bloc file
                      copy:
                              content: 'this is a rescue operation for my failed block'
                              dest: /tmp/myfailedblockfile
...
