---
- name: configuring the /etc/hosts on all managed nodes
  hosts: all
  become: true
  tasks:
          - name: copy /etc/hosts from controlnode to managed nodes
            copy:
                    src: /etc/hosts
                    dest: /etc/hosts
                    owner: root
                    group: root
                    mode: '0644'
...

