---
- name: generate a hashed password
  hosts: balancer
  become: false
  tasks:
          - name: generate a password
            copy:
                    content: "{{ 'mypassword' | hash('sha512') }}"
                    dest: /tmp/mypassword
...
