---
- name: test importing a role
  hosts: balancer
  become: true
  vars:
          mydata: "{{ 'lookup','file','/etc/passwd' }}"
          home: Jerusalem
  tasks:
          - name: run a debug module
            debug:
                    msg: "Welcome to {{ home }}"
          - name: import a playbook
            import_role:
                    name: third-apache-role
          - name: run a second debug module
            debug:
                    msg: "Does this message appear last"

