---
- name: inastall, start, add firewall, create privdir, index.html, selinux, restart service
  hosts: webservers
  become: true
  tasks:
          - name: install apache
            yum:
                    name: httpd
                    state: latest
            tags:
                    - restartapache

          - name: start the service
            service:
                    name: httpd
                    state: started
                    enabled: true
            tags:
                    - startapache
          - name: add httpd to firewall
            firewalld:
                    service: http
                    permanent: true
                    immediate: true
                    state: enabled
            tags:
                    - firewallapache
          - name: create new privdir
            file:
                    path: /var/www/privdir
                    state: directory
            tags:
                    - createdir

          - name: add index file to privdir
            file:
                    path: /var/www/privdir/index.html
                    state: touch
                    owner: root
                    group: root
                    mode: 0644
          - name: add content to the index file
            copy:
                    content: 'This site is private to Andrew Taku'
                    dest: /var/www/privdir/index.html
          - name: set the proper selinux file context type
            sefcontext:
                    target: '/var/www/privdir(/.*?)'
                    ftype: d
                    setype: httpd_sys_content_t
                    reload: true
          - name: restore selinux file context
            command: restorecon -irv /var/www/privdir

          - name: create a virtualhosts file
            copy:
                    src: /etc/httpd/conf.d/_virtual.conf
                    dest: /etc/httpd/conf.d/_virtual.conf

          - name: restart httpd service
            service:
                    name: httpd
                    state: restarted

             
...
            
