---
# handlers file for haproxy
- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded

# handlers file for firewall

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded


