---
- name: first of two plays
  hosts: balancer
  become: true
  become_method: sudo
  remote_user: ansible
  tasks:
          - name: install http
            yum:
                    name:
                            - httpd
                            - firewalld
                    state: present
          - name: change the index.html file
            copy:
                    content: "Welcome to multiple plays!\n"
                    dest: /var/www/html/index.html
          - name: start the service
            service:
                    name: "{{ item  }}"
                    state: started
                    enabled: true
            loop:
                    - httpd
                    - firewalld
          - name: add the service to the firewall
            firewalld:
                    service: http
                    immediate: yes
                    permanent: true
                    state: enabled
- name: second play
  hosts: localhost
  become: no
  tasks:
          - name: test the website
            uri:
                    url: http://managednode1.example.com
                    return_content: yes
                    status_code: 200

                    




