---
- name: create users by looping
  hosts: balancer
  become: yes
  vars:
          users:
                  - linuxuser1
                  - linuxuser2
                  - linuxuser3
  tasks:
          - name: create users
            user:
                    name: "{{ item }}"
                    state: absent
                    remove: yes
            loop:
                    "{{ users }}"

