---
- name: create users 
  hosts: balancer
  become: yes
  vars_files:
          - secrets2.yml
  tasks:
          - name: create the groups
            group:
                    name: "{{ item }}"
                    state: present
            with_items:
                    - dba
                    - sysadmin
          - name: create the users
            user:
                    name: "{{ username }}"
                    groups: "{{ group }}"
                    password: "{{ password }}"
                    state: present
                    append: yes
                    generate_ssh_key: yes
                    ssh_key_bits: 4096
                    ssh_key_file: .ssh/id_rsa
