---
- name: Install and configure a webserver with basic authentication
  hosts: balancer
  become: yes
  vars:
          - firewall_pkg: firewalld
          - firewall_svc: firewalld
          - web_pkg: httpd
          - web_svc: httpd
          - ssl_pkg: mod_ssl
          - httpdconf_src: files/httpd.conf
          - httpdconf_dest: /etc/httpd/conf/httpd.conf
          - htaccess_src: files/.htaccess
          - secrets_dir: /etc/httpd/secrets
          - secrets_src: files/htpasswd
          - secrets_dest: "{{ secrets_dir }}/htpasswd"
          - web_root: /var/www/html
  tasks:
          - name: Install latest version of packages
            yum:
                    name:
                            - "{{ firewall_pkg }}"
                            - "{{ web_pkg }}"
                            - "{{ ssl_pkg }}"
                    state: latest
          - name: Configure webservice
            copy:
                    src: "{{ httpdconf_src }}"
                    dest: "{{ httpdconf_dest }}"
                    owner: root
                    group: root
                    mode: 0644
          - name: secrets directory exists
            file:
                    path: "{{ secrets_dir }}"
                    state: directory
                    owner: apache
                    group: apache
                    mode: 0500
          - name: htpasswd file exists
            copy:
                    src: "{{ secrets_src }}"
                    dest: "{{ secrets_dest }}"
                    owner: apache
                    group: apache
                    mode: 0400
          - name: .htaccess file installed in doc root
            copy:
                    src: "{{ htaccess_src }}"
                    dest: "{{ web_root }}/.htaccess"
                    owner: apache
                    group: apache
                    mode: 0400
          - name: create index.html
            copy:
                    content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts.default_ipv4.address }}) has been customized by ansible.\n"
                    dest: "{{ web_root }}/index.html"
          - name: firewall service enabled and started
            service:
                    name: "{{ firewall_svc }}"
                    enabled: true
                    state: started
          - name: Open the port for the webserver
            firewalld:
                    service: https
                    immediate: yes
                    permanent: true
                    state: enabled
          - name: web service enabled and started
            service:
                    name: "{{ web_svc }}"
                    enabled: yes
                    state: started
