---
# tasks file for ntprole
- name: do this only on managednode1 which is the timeserver
  debug:
          msg: 'This runs only on managednode1.example.com'
- name: Install and configure ntp/chrony
  yum:
          name: chrony
          state: latest
- name: start and enable the service
  service:
          name: chronyd
          state: started
          enabled: true
- name: add ntp to the firewall
  firewalld:
          service: ntp
          immediate: true
          permanent: true
          state: enabled
- name: edit the chrony.conf file
  lineinfile:
          path: /etc/chrony.conf
          regexp: '^pool'
          line: "{{ item }}"
          state: present
  loop:
          - 'server 0.in.pool.ntp.org'
          - 'server 1.in.pool.ntp.org'
          - 'server 2.in.pool.ntp.org'
          - 'server 3.in.pool.ntp.org'
- name: allow the network to sync with chrony
  lineinfile:
          path: /etc/chrony.conf
          regexp: '#allow 192.168.0.0/16'
          line: 'allow 172.24.1.0/24'
          state: present
  notify: restart server chronyd

